---
label: production
hide_body: false
fields:
- type: text
  name: title
  label: Title
- type: datetime
  name: date
  label: Date
- type: textarea
  name: description
  label: Description
- type: image_gallery
  name: images
  label: Images
  description: The first image will be shown at the top of the page
- type: boolean
  name: feature_image
  label: Feature Image
  description: If you turn this off the image will show in the body copy instead of
    the top of the page
  hidden: false
  default: true
- type: text
  name: image_credit
  label: Image Credit
- type: field_group_list
  label: People
  name: people
  fields:
  - type: select
    name: contributor
    config:
      source:
        type: pages
        section: contributors
    label: Contributor
  - type: text
    name: role
    label: Role
pages:
- content/production/_index.md
- content/production/abide.md
- content/production/brooklyn-all-american.md
- content/production/forbidden-cuba.md
- content/production/griffins-ghost.md
- content/production/judas-horse.md
- content/production/proud-mary.md
- content/production/the-night-swimmer.md
- content/production/the-whole-story-podcast.md
- content/production/yankee-tripper.md
- content/production/year-of-the-spy.md
